
- name: Install jq in AWX
  delegate_to: 127.0.0.1
  yum:
    name: jq
    state: latest
    
- name: Collect AWX admin token the hard way!
  delegate_to: 127.0.0.1
  shell: |
      curl -sku {{ tower_username }}:{{ tower_password }} -H "Content-Type: application/json" -X POST -d '{"description":"Tower CLI", "application":null, "scope":"write"}' https://{{ tower_host }}/api/v2/users/1/personal_tokens/ | jq '.token' | sed -r 's/\"//g'
  register: tower_token
  no_log: True

- name: Remove 'Ansible Provision Server' project to users organisation
  awx.awx.tower_project:
    name: "{{ member_id }} - Ansible Provision Server"
    description: "Creates digitalocean droplet and space, performs initial setup, adds relevant playbooks to users account."
    organization: "{{ member_id }}"
    scm_type: git
    scm_url: "https://gitlab.com/GoMatrixHosting/ansible-provision-server.git"
    scm_delete_on_update: yes
    state: absent
    tower_host: "https://{{ tower_host }}"
    tower_oauthtoken: "{{ tower_token.stdout }}"
    validate_certs: yes

- name: Remove 'Spantaleev's Deploy' project to users organisation
  awx.awx.tower_project:
    name: "{{ member_id }} - Matrix Docker Ansible Deploy"
    description: "Creating and updating a Matrix service on an already provisioned server."
    organization: "{{ member_id }}"
    scm_type: git
    scm_url: "https://gitlab.com/GoMatrixHosting/gomatrixhosting-matrix-docker-ansible-deploy.git"
    scm_delete_on_update: yes
    state: absent
    tower_host: "https://{{ tower_host }}"
    tower_oauthtoken: "{{ tower_token.stdout }}"
    validate_certs: yes

- name: Delete AWX user from team
  awx.awx.tower_role:
    user: "{{ client_email }}"
    target_team: "{{ member_id }}"
    role: member
    state: absent
    tower_host: "https://{{ tower_host }}"
    tower_oauthtoken: "{{ tower_token.stdout }}"
    validate_certs: yes

- name: Delete AWX user
  awx.awx.tower_user:
    username: "{{ client_email }}"
    email: "dummyvalue@protonmail.com"
    state: absent
    tower_host: "https://{{ tower_host }}"
    tower_oauthtoken: "{{ tower_token.stdout }}"
    validate_certs: yes

- name: Delete AWX team
  awx.awx.tower_team:
    name: "{{ member_id }}"
    organization: "{{ member_id }}"
    state: absent
    tower_host: "https://{{ tower_host }}"
    tower_oauthtoken: "{{ tower_token.stdout }}"
    validate_certs: yes

- name: Delete AWX organisation
  awx.awx.tower_organization:
    name: "{{ member_id }}"
    description: "{{ client_email }} Organisation"
    state: absent
    tower_host: "https://{{ tower_host }}"
    tower_oauthtoken: "{{ tower_token.stdout }}"
    validate_certs: yes
  register: awxorg

