    
- name: Delete the organisations directory on AWX
  shell: "rm -r /var/lib/awx/projects/clients/{{ member_id }}"

- name: Ensure group "webhook" exists
  group:
    name: webhook
    state: present
    
- name: Remove bound entry for user from client-list file
  lineinfile:
    dest: '/var/lib/awx/projects/clients/client-list'
    line: '{{ member_id }},{{ client_email }},bound'
    mode: '0660'
    owner: root
    group: webhook
    state: absent
    
- name: Remove non-bound entry for user from client-list file
  lineinfile:
    dest: '/var/lib/awx/projects/clients/client-list'
    line: '{{ member_id }},{{ client_email }}'
    mode: '0660'
    owner: root
    group: webhook
    state: absent
