
- name: Include hosting vars of digital_ocean.yml
  include_vars:
    file: /var/lib/awx/projects/hosting/hosting_vars.yml

- name: Include organisation variables from organisation.yml
  include_vars:
    file: /var/lib/awx/projects/clients/{{ member_id }}/organisation.yml
