
- name: "Binds an enterprise user to the appropriate team upon first login."
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Include hosting vars
      include_vars:
        file: /var/lib/awx/projects/hosting/hosting_vars.yml
      no_log: True

    - name: Include AWX master token from awx_tokens.yml
      include_vars:
        file: /var/lib/awx/projects/hosting/awx_tokens.yml
      no_log: True

    - name: Create a AWX session token for executing modules
      awx.awx.tower_token:
        description: 'AWX Session Token'
        scope: "write"
        state: present
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_master_token }}"
      register: awx_session_token
      no_log: True

    - debug:
        msg: "{{ client_email }}"

    - debug:
        msg: "{{ member_id }}"
        
    - debug:
        msg: "{{ awx_session_token.ansible_facts.tower_token.token }}"

    - name: Add enterprise user to the appropriate team
      awx.awx.tower_role:
        user: "{{ client_email }}"
        target_team: "{{ member_id }}"
        role: member
        state: present
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
        validate_certs: yes

    - name: Delete the AWX session token for executing modules
      awx.awx.tower_token:
        description: 'AWX Session Token'
        scope: "write"
        state: absent
        existing_token_id: "{{ awx_session_token.ansible_facts.tower_token.id }}"
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
