
- name: "Deletes the remaining '<< SUBSCRIPTION DELETION IN PROGRESS >>' template."
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Pause for 10 seconds to the previous job can finish
      pause:
       seconds: 10

    - name: Collect AWX admin token the hard way!
      delegate_to: 127.0.0.1
      shell: |
          curl -sku {{ tower_username }}:{{ tower_password }} -H "Content-Type: application/json" -X POST -d '{"description":"Tower CLI", "application":null, "scope":"write"}' https://{{ tower_host }}/api/v2/users/1/personal_tokens/ | jq '.token' | sed -r 's/\"//g'
      register: tower_token
#      no_log: True 

    - name: Remove '<< SUBSCRIPTION DELETION IN PROGRESS >>' job template
      delegate_to: 127.0.0.1
      awx.awx.tower_job_template:
        name: "0 - {{ subscription_id }} - << SUBSCRIPTION DELETION IN PROGRESS >>"
        job_type: run
        project: "{{ member_id }} - Matrix Docker Ansible Deploy"
        playbook: setup.yml
        state: absent
        tower_host: "https://{{ tower_host }}"
        tower_oauthtoken: "{{ tower_token.stdout }}"
        validate_certs: yes
