
- name: "Deletes the remaining '<< SUBSCRIPTION DELETION IN PROGRESS >>' template."
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Pause for 10 seconds to the previous job can finish
      pause:
       seconds: 10

    - name: Include hosting vars
      include_vars:
        file: /var/lib/awx/projects/hosting/hosting_vars.yml
      no_log: True

    - name: Include AWX master token from awx_tokens.yml
      include_vars:
        file: /var/lib/awx/projects/hosting/awx_tokens.yml
      no_log: True

    - name: Create a AWX session token for executing modules
      awx.awx.tower_token:
        description: 'AWX Session Token'
        scope: "write"
        state: present
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_master_token }}"
      register: awx_session_token
      no_log: True

    - name: Remove Matrix server from organisations inventory
      delegate_to: 127.0.0.1
      awx.awx.tower_host:
        name: "matrix.{{ matrix_domain }}"
        description: "{{ matrix_domain }} Matrix Server"
        inventory: "{{ member_id }}"
        state: absent
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
        validate_certs: yes
      when: matrix_domain is defined
  
    - name: Remove Wireguard Server from organisations inventory
      delegate_to: 127.0.0.1
      awx.awx.tower_host:
        name: "wireguard.{{ matrix_domain }}"
        description: "{{ matrix_domain }} Wireguard Proxy"
        inventory: "{{ member_id }}"
        state: absent
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
        validate_certs: yes
      when: matrix_domain is defined

    - name: Remove '<< SUBSCRIPTION DELETION IN PROGRESS >>' job template
      delegate_to: 127.0.0.1
      awx.awx.tower_job_template:
        name: "0 - {{ subscription_id }} - << SUBSCRIPTION DELETION IN PROGRESS >>"
        job_type: run
        project: "Ansible Create Delete Subscription Membership"
        playbook: delete_subscription.yml
        state: absent
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
        validate_certs: yes

    - name: Delete the AWX session token for executing modules
      awx.awx.tower_token:
        description: 'AWX Session Token'
        scope: "write"
        state: absent
        existing_token_id: "{{ awx_session_token.ansible_facts.tower_token.id }}"
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"

    - name: Delete the cleanup_deletion_template extra variables file
      delegate_to: 127.0.0.1
      file:
        path: '/var/lib/awx/projects/hosting/cleanup_deletion_template-{{ subscription_id }}.json'
        state: absent
