
#
# IPO Summary:
#
# INPUT: member_id, subscription_id
# PROCESSING: Removes job templates, digitalocean resources, and files/folders associated with a subscription.
# OUTPUT: 
#

- name: "Removes job templates, digitalocean resources, and files/folders associated with a subscription."
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - delete-server-and-templates
    - delete-awx-account-and-files

