
- name: "Checks for updates hourly, if ones available it applies it to every Matrix server connected to AWX."
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Generate list of deploy/update job templates
      shell: |
        cat /var/lib/awx/projects/clients/*/*/server_vars.yml | grep matrix_domain | sed 's/^matrix_domain: //g' | sed -r 's/$/ - 0 - Deploy\/Update a Server/g'
      register: deploy_templates

    - name: Include hosting vars of hosting_vars.yml
      include_vars:
        file: /var/lib/awx/projects/hosting/hosting_vars.yml
      no_log: True

    - name: Include AWX master token from awx_tokens.yml
      include_vars:
        file: /var/lib/awx/projects/hosting/awx_tokens.yml
      no_log: True

    - name: Clone the deploy repo to see if it's updated
      git:
        repo: "{{ deploy_source }}"
        dest: /tmp/matrix-docker-ansible-deploy
        force: yes
      register: update_result

    - name: Set deploy_all fact
      set_fact:
        deploy_all: True
      when: (update_result.before != update_result.after) and (update_result.before)

    - name: Set deploy_all fact
      set_fact:
        deploy_all: False
      when: (update_result.before == update_result.after) or (not update_result.before)

    - name: Create a AWX session token for executing modules
      awx.awx.tower_token:
        description: 'AWX Session Token'
        scope: "write"
        state: present
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_master_token }}"
      register: awx_session_token

    - name: Execute every job template sequentially
      include_tasks: deploy.yml 
      loop: "{{ deploy_templates.stdout_lines | flatten(levels=1) }}"
      when: deploy_all|bool

    - name: Delete the AWX session token for executing modules
      awx.awx.tower_token:
        description: 'AWX Session Token'
        scope: "write"
        state: absent
        existing_token_id: "{{ awx_session_token.ansible_facts.tower_token.id }}"
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
