
- name: "Checks for updates regularly, if ones available it updates SCM projects for deploy stage jobs, then applies that update to every Matrix server connected to AWX."
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Include hosting vars of hosting_vars.yml
      include_vars:
        file: /var/lib/awx/projects/hosting/hosting_vars.yml
      no_log: True

    - name: Clone the deploy repo to see if it's updated
      git:
        repo: "{{ deploy_source }}"
        dest: /tmp/matrix-docker-ansible-deploy
        force: yes
      register: update_result

    - name: Set deploy_all fact
      set_fact:
        deploy_all: True
      when: ( ( update_result.before != update_result.after ) and ( update_result.before ) ) or ( force_update | bool )

    - name: Set deploy_all fact
      set_fact:
        deploy_all: False
      when: ( ( update_result.before == update_result.after ) or ( not update_result.before ) ) and ( not force_update | bool )

    - name: Include AWX master token from awx_tokens.yml
      include_vars:
        file: /var/lib/awx/projects/hosting/awx_tokens.yml
      when: deploy_all | bool
      no_log: True

    - name: Create a AWX session token for executing modules
      awx.awx.tower_token:
        description: 'AWX Session Token'
        scope: "write"
        state: present
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_master_token }}"
      when: deploy_all | bool
      register: awx_session_token
      no_log: True

    - name: Install jq in AWX
      delegate_to: 127.0.0.1
      yum:
        name: jq
        state: latest
      when: deploy_all | bool

    - name: Generate a list of member_ids
      shell: |
        jq -r '.member_id' /var/lib/awx/projects/clients/*/*/extra_vars.json | sort -u
      when: deploy_all | bool
      register: list_member_ids

    - name: Execute every job template sequentially (update projects)
      include_tasks: deploy_scm.yml 
      loop: "{{ list_member_ids.stdout_lines | flatten(levels=1) }}"
      when: deploy_all | bool

    - name: Generate list of deploy/update job templates
      shell: |
        cat /var/lib/awx/projects/clients/*/*/server_vars.yml | grep matrix_domain | sed 's/^matrix_domain: //g' | sed -r 's/$/ - 0 - Deploy\/Update a Server/g'
      when: deploy_all | bool
      register: deploy_templates

    - name: Execute every job template sequentially (launch all deploys)
      include_tasks: job_launch.yml 
      loop: "{{ deploy_templates.stdout_lines | flatten(levels=1) }}"
      when: deploy_all | bool
      ignore_errors: yes

    - name: Delete the AWX session token for executing modules
      awx.awx.tower_token:
        description: 'AWX Session Token'
        scope: "write"
        state: absent
        existing_token_id: "{{ awx_session_token.ansible_facts.tower_token.id }}"
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
      when: deploy_all | bool
