
- name: "Performs initial organisation/team creation before subscription is confirmed."
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create AWX organisation
      tower_organization:
        name: "{{ member_id }}"
        description: "{{ client_email }} Organisation"
        tower_host: "{{ tower_host }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        validate_certs: yes
    
    - name: Create a team for the user
      tower_team:
        name: "{{ member_id }}"
        description: "{{ client_email }} Team"
        organization: "{{ member_id }}"
        state: present
        tower_host: "{{ tower_host }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        validate_certs: yes
