
- name: "Performs initial organisation/team creation before subscription is confirmed."
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Include hosting vars
      include_vars:
        file: /var/lib/awx/projects/hosting/hosting_vars.yml
      no_log: True

    - name: Include AWX master token from awx_tokens.yml
      include_vars:
        file: /var/lib/awx/projects/hosting/awx_tokens.yml
      no_log: True

    - name: Create a AWX session token for executing modules
      awx.awx.tower_token:
        description: 'AWX Session Token'
        scope: "write"
        state: present
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_master_token }}"
      register: awx_session_token

    - name: Create AWX organisation
      awx.awx.tower_organization:
        name: "{{ member_id }}"
        description: "{{ client_email }} Organisation"
        state: present
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
        validate_certs: yes
    
    - name: Create a Team for the user
      awx.awx.tower_team:
        name: "{{ member_id }}"
        description: "{{ client_email }} Team"
        organization: "{{ member_id }}"
        state: present
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
        validate_certs: yes

    - name: Delete the AWX session token for executing modules
      awx.awx.tower_token:
        description: 'AWX Session Token'
        scope: "write"
        state: absent
        existing_token_id: "{{ awx_session_token.ansible_facts.tower_token.id }}"
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
