
- name: "Re-provisions every Matrix server connected to AWX."
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Install jq in AWX
      yum:
        name: jq
        state: latest

    - name: Generate list of backup job templates
      shell: |
        cat /var/lib/awx/projects/clients/*/*/extra_vars.json | jq -r '.member_id,.subscription_id' | sed "N;s/\n/,/"
      register: provision_templates

    - name: Include hosting vars
      include_vars:
        file: /var/lib/awx/projects/hosting/hosting_vars.yml
      no_log: True

    - name: Collect AWX admin token the hard way!
      delegate_to: 127.0.0.1
      shell: |
          curl -sku {{ tower_username }}:{{ tower_password }} -H "Content-Type: application/json" -X POST -d '{"description":"Tower CLI", "application":null, "scope":"write"}' https://{{ tower_host }}/api/v2/users/1/personal_tokens/ | jq '.token' | sed -r 's/\"//g'
      register: tower_token
      no_log: True 

    - name: Execute every job template sequentially
      include_tasks: reprovision.yml 
      loop: "{{ provision_templates.stdout_lines | flatten(levels=1) }}"
