
- name: "Re-provisions every Matrix server connected to AWX."
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Install jq in AWX
      delegate_to: 127.0.0.1
      yum:
        name: jq
        state: latest

    - name: Generate list of backup job templates
      shell: |
        jq -r '.member_id,.subscription_id' /var/lib/awx/projects/clients/*/*/extra_vars.json | sed "N;s/\n/,/"
      register: provision_templates

    - name: Include hosting vars
      include_vars:
        file: /var/lib/awx/projects/hosting/hosting_vars.yml
      no_log: True

    - name: Include AWX master token from awx_tokens.yml
      include_vars:
        file: /var/lib/awx/projects/hosting/awx_tokens.yml
      no_log: True

    - name: Create a AWX session token for executing modules
      awx.awx.tower_token:
        description: 'AWX Session Token'
        scope: "write"
        state: present
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_master_token }}"
      register: awx_session_token
      no_log: True

    - debug:
        msg: "{{ provision_templates.stdout_lines }}"

    - name: Execute every job template sequentially
      include_tasks: reprovision.yml 
      loop: "{{ provision_templates.stdout_lines | flatten(levels=1) }}"

    - name: Delete the AWX session token for executing modules
      awx.awx.tower_token:
        description: 'AWX Session Token'
        scope: "write"
        state: absent
        existing_token_id: "{{ awx_session_token.ansible_facts.tower_token.id }}"
        tower_host: "https://{{ awx_host }}"
        tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
