
- name: Set swap size for Wireguard Server
  delegate_to: 127.0.0.1
  set_fact:
    swap_size: "1G"

- name: Test if SSH is possible with ipv4
  delegate_to: "{{ server_ip }}"
  command: echo success
  register: echo_output
  
- debug:
    msg: "{{ echo_output.stdout }}"

- name: Disable password authentication
  delegate_to: "{{ server_ip }}"
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PasswordAuthentication no'

- name: Restart SSH
  delegate_to: "{{ server_ip }}"
  service:
    name: ssh
    state: restarted

