
- name: Set swap size for Wireguard Server
  delegate_to: 127.0.0.1
  set_fact:
    swap_size: "1G"

- name: Test if SSH is possible
  delegate_to: "{{ server_ip }}"
  command: echo success
  register: echo_output
  
- debug:
    msg: "{{ echo_output.stdout }}"

- name: Disable password authentication
  delegate_to: "{{ server_ip }}"
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PasswordAuthentication no'

- name: Change SSH port for wireguard server
  delegate_to: "{{ server_ip }}"
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'Port 2222'

- name: Set the new authorized key taken from file
  delegate_to: "{{ server_ip }}"
  authorized_key:
    user: root
    state: present
    exclusive: yes
    key: "{{ lookup('file', '/var/lib/awx/projects/hosting/client_public.key') }}"
  when: update_ssh_key | bool

- name: Set boolean value to exit playbook
  set_fact:
    end_playbook: true
  when: update_ssh_key | bool

- name: End playbook if this task list is called.
  meta: end_play
  when: ( end_playbook is defined ) and ( end_playbook | bool ) and ( update_ssh_key | bool )
