
- name: Calculate spaces for printing DNS records
  delegate_to: 127.0.0.1
  connection: local
  command: |
    perl -e 'print " " x (23 - length( '{{ matrix_domain }}' ))';
  register: dns_spaces

- debug:
    msg: 
    - Your Wireguard server has been created. We recommend that you configure your DNS to have the 
    - "following records:"
    - Type    Host                              Target
    - A/AAAA  wireguard.{{ matrix_domain }}{{ dns_spaces.stdout }}{{ server_ip }}
