
- name: Update repositories and all packages on target machine
  delegate_to: "{{ server_ip }}"
  apt:
    name: "*"
    update_cache: yes

- name: Update all packages to their latest version
  delegate_to: "{{ server_ip }}"
  apt:
    name: "*"
    state: latest

- name: Add buster-backports repository into sources list
  delegate_to: "{{ server_ip }}"
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    state: present

- name: Install necessary utils on wireguard server
  delegate_to: "{{ server_ip }}"
  apt:
    pkg:
     - wireguard
    default_release: buster-backports

- name: Collect kernel version
  delegate_to: "{{ server_ip }}"
  shell: uname -r
  register: kernel_version

- name: Install Linux headers on wireguard server
  delegate_to: "{{ server_ip }}"
  apt:
    pkg:
     - "linux-headers-{{ kernel_version.stdout }}"
  ignore_errors: True

- name: Create swapfile with the right permissions
  delegate_to: "{{ server_ip }}"
  command: 'fallocate -l {{ swap_size }} /swapfile'
  register: swapfile_new
  args:
    creates: /swapfile
    
- name: Set correct permissions on swapfile
  delegate_to: "{{ server_ip }}"
  command: 'chmod 600 /swapfile'
  when: swapfile_new.delta is defined

- name: Make swapfile
  delegate_to: "{{ server_ip }}"
  command: 'mkswap /swapfile'
  when: swapfile_new.delta is defined
  
- name: Make swapfile
  delegate_to: "{{ server_ip }}"
  command: 'swapon /swapfile'
  when: swapfile_new.delta is defined

- name: Make swapfile permanent in /etc/fstab
  delegate_to: "{{ server_ip }}"
  mount: name=none
         src=/swapfile
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present

- name: Set swappiness to 20
  delegate_to: "{{ server_ip }}"
  shell: sysctl vm.swappiness=20

- name: Set swappiness to 20 on reboot
  delegate_to: "{{ server_ip }}"
  lineinfile:
    path: /etc/sysctl.conf
    line: vm.swappiness=20
    owner: root
    group: root
    mode: '0644'

