
- name: Include hosting vars of hosting_vars.yml
  include_vars:
    file: /var/lib/awx/projects/hosting/hosting_vars.yml
  no_log: True

- name: Set valid digitalocean area code for New York City.
  delegate_to: 127.0.0.1
  set_fact:
    do_droplet_region: "nyc1"
  when: wireguard_droplet_region_long == "New York City (USA)"

- name: Set valid digitalocean area code for San Francisco.
  delegate_to: 127.0.0.1
  set_fact:
    do_droplet_region: "sfo3"
  when: wireguard_droplet_region_long == "San Francisco (USA)"

- name: Set valid digitalocean area code for Amsterdam.
  delegate_to: 127.0.0.1
  set_fact:
    do_droplet_region: "ams3"
  when: wireguard_droplet_region_long == "Amsterdam (NLD)"

- name: Set valid digitalocean area code for Frankfurt.
  delegate_to: 127.0.0.1
  set_fact:
    do_droplet_region: "fra1"
  when: wireguard_droplet_region_long == "Frankfurt (DEU)"

- name: Set valid digitalocean area code for Singapore.
  delegate_to: 127.0.0.1
  set_fact:
    do_droplet_region: "sgp1"
  when: wireguard_droplet_region_long == "Singapore (SGP)"

- name: Set valid digitalocean area code for London.
  delegate_to: 127.0.0.1
  set_fact:
    do_droplet_region: "lon1"
  when: wireguard_droplet_region_long == "London (GBR)"

- name: Set valid digitalocean area code for Toronto.
  delegate_to: 127.0.0.1
  set_fact:
    do_droplet_region: "tor1"
  when: wireguard_droplet_region_long == "Toronto (CAN)"

- name: Set valid digitalocean area code for Balgalore.
  delegate_to: 127.0.0.1
  set_fact:
    do_droplet_region: "blr1"
    matrix_jitsi_timezone: "Asia/Kolkata"
  when: wireguard_droplet_region_long == "Balgalore (IND)"
  
- name: Set server variables for Wireguard Server
  delegate_to: 127.0.0.1
  set_fact:
    slug_size: "s-1vcpu-1gb"
    swap_size: "1G"

- name: Record the public SSH key into a variable
  set_fact:
    public_ssh_key: "{{ lookup('file', '/var/lib/awx/projects/hosting/client_public.key') }}"

- debug:
    msg: "The public SSH key to check for: {{ public_ssh_key }}"

- name: 
  delegate_to: 127.0.0.1
  community.digitalocean.digital_ocean_sshkey_info:
    oauth_token: '{{ do_api_token }}'
  register: ssh_keys
  
- name: Build an array with the correct SSH ID
  delegate_to: 127.0.0.1
  set_fact:
    ssh_key_id_array: "{{ ssh_key_id_array }} + [ '{{ item.id }}' ]"
  when: item.public_key == public_ssh_key
  loop: "{{ ssh_keys.data|flatten(levels=1) }}"

- debug:
    msg: "{{ ssh_key_id_array }}"

- name: Spawn a new Digital Ocean Droplet
  delegate_to: 127.0.0.1
  community.digitalocean.digital_ocean_droplet:
    state: present
    name: 'wireguard.{{ matrix_domain }}'
    oauth_token: '{{ do_api_token }}'
    size: '{{ slug_size }}'
    ssh_keys: '{{ ssh_key_id_array }}'
    region: '{{ wireguard_droplet_region }}'
    image: '{{ do_image }}'
    ipv6: yes
    wait: yes
    unique_name: yes

- debug:
    msg: "{{ new_server_info }}"

- debug:
    msg: "{{ new_server_info.data.droplet }}"

- name: Assign server IPs to variables
  delegate_to: 127.0.0.1
  set_fact:
    server_ipv4: "{{ new_server_info.data.ip_address }}"
    server_ipv6: "{{ new_server_info.data.ipv6_address }}"

- debug:
    msg: "{{ server_ipv4 }}"

- debug:
    msg: "{{ server_ipv6 }}"
