
- name: Install jq in AWX
  delegate_to: 127.0.0.1
  yum:
    name: jq
    state: latest
    
- name: Create a AWX session token for executing modules
  awx.awx.tower_token:
    description: 'AWX Session Token'
    scope: "write"
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_master_token }}"
  register: awx_session_token

- name: Remove 'Ansible Provision Server' project from users organisation
  awx.awx.tower_project:
    name: "{{ member_id }} - Ansible Provision Server"
    description: "Creates digitalocean droplet and space, performs initial setup, adds relevant playbooks to users account."
    organization: "{{ member_id }}"
    scm_type: git
    scm_url: "https://gitlab.com/GoMatrixHosting/ansible-provision-server.git"
    scm_delete_on_update: yes
    state: absent
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  ignore_errors: True

- name: Remove 'Spantaleev's Deploy' project from users organisation
  awx.awx.tower_project:
    name: "{{ member_id }} - Matrix Docker Ansible Deploy"
    description: "Creating and updating a Matrix service on an already provisioned server."
    organization: "{{ member_id }}"
    scm_type: git
    scm_url: "https://gitlab.com/GoMatrixHosting/gomatrixhosting-matrix-docker-ansible-deploy.git"
    scm_delete_on_update: yes
    state: absent
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  ignore_errors: True

- name: Delete AWX user from team
  awx.awx.tower_role:
    user: "{{ client_email }}"
    target_team: "{{ member_id }}"
    role: member
    state: absent
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: client_email is defined
  ignore_errors: True

- name: Delete AWX user
  awx.awx.tower_user:
    username: "{{ client_email }}"
    email: "dummyvalue@protonmail.com"
    state: absent
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: client_email is defined

- name: Delete AWX team
  awx.awx.tower_team:
    name: "{{ member_id }}"
    organization: "{{ member_id }}"
    state: absent
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  ignore_errors: True

- name: Delete AWX organisation
  awx.awx.tower_organization:
    name: "{{ member_id }}"
    description: "{{ client_email }} Organisation"
    state: absent
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: client_email is defined
  register: awxorg

- name: Delete the AWX session token for executing modules
  awx.awx.tower_token:
    description: 'AWX Session Token'
    scope: "write"
    state: absent
    existing_token_id: "{{ awx_session_token.ansible_facts.tower_token.id }}"
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
