
- name: Include hosting vars of digital_ocean.yml
  include_vars:
    file: /var/lib/awx/projects/hosting/hosting_vars.yml
  no_log: True

- name: Include AWX master token from awx_tokens.yml
  include_vars:
    file: /var/lib/awx/projects/hosting/awx_tokens.yml
  no_log: True

- name: Include organisation variables from organisation.yml
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - /var/lib/awx/projects/clients/{{ member_id }}/organisation.yml
      skip: true
