
- name: Configure byo_bool 2
  set_fact:
    byo_bool: false

- name: Configure byo_bool 2 (when 'byo' in subscription_id do)
  set_fact:
    byo_bool: true
  when: subscription_id.find('v=' ~ 'byo') == -1

- name: Generate string to append to byo
  delegate_to: 127.0.0.1
  command: openssl rand -hex 7
  register: subscription_hex
  when: subscription_id.find('v=' ~ 'byo') == -1

- name: Append string to byo
  delegate_to: 127.0.0.1
  command: echo "{{ subscription_id }}-{{ subscription_hex }}"
  register: subscription_id
  when: subscription_id.find('v=' ~ 'byo') == -1

- name: Create a directory if it does not exist locally on AWX
  delegate_to: 127.0.0.1
  file:
    path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/'
    state: directory
    mode: '0700'

# Create server_vars.yml file locally on AWX.

- name: Set slug_size for plan
  set_fact:
    slug_size: "s-1vcpu-1gb"
    swap_size: "2G"
  when: plan_title=="Micro Server"

- name: Set slug_size for plan
  set_fact:
    slug_size: "s-1vcpu-2gb"
    swap_size: "2G"
  when: plan_title=="Small Server"

- name: Set slug_size for plan
  set_fact:
    slug_size: "s-2vcpu-4gb"
    swap_size: "4G"
  when: plan_title=="Medium Server"

- name: Set slug_size for plan
  set_fact:
    slug_size: "s-4vcpu-8gb"
    swap_size: "8G"
  when: plan_title=="Large Server"

- name: Set slug_size for plan
  set_fact:
    slug_size: "s-8vcpu-32gb"
    swap_size: "32G"
  when: plan_title=="Jumbo Server"

- name: Add do_image line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'do_image: {{ do_image_master }}'
    mode: '0600'
    state: present
    create: yes

- name: Add slug_size line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'slug_size: {{ slug_size }}'
    mode: '0600'
    state: present

- name: Add swap_size line to server_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'swap_size: {{ swap_size }}'
    mode: '0600'
    state: present

# Create organisation.yml file, generate password if needed.

- name: Check if organisation.yml file already exists on AWX
  delegate_to: 127.0.0.1
  stat: 
    path: '/var/lib/awx/projects/clients/{{ member_id }}/organisation.yml'
  register: orgfile

- name: Set generate_password to true if organisation.yml doesn't exist
  set_fact:
    generate_password: true
  when: orgfile.stat.exists == false

- name: Install pwgen on tower with yum
  delegate_to: 127.0.0.1
  yum:
    name: pwgen
    state: latest
  when: orgfile.stat.exists == false

- name: Generate the users password
  delegate_to: 127.0.0.1
  command: 'pwgen -s 16 1'
  register: register_client_password
  when: orgfile.stat.exists == false

- name: Add client_password line to organisation.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/organisation.yml'
    line: 'client_password: "{{ register_client_password.stdout }}"'
    mode: '0600'
    state: present
    create: yes
  when: orgfile.stat.exists == false

- name: Set client_password within playbook for account creation
  set_fact:
    client_password: "{{ register_client_password.stdout }}"
  when: orgfile.stat.exists == false

- name: Add client_email line to organisation.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/organisation.yml'
    line: 'client_email: "{{ client_email }}"'
    mode: '0600'
    state: present

- name: Add member_id line to organisation.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/organisation.yml'
    line: 'member_id: "{{ member_id }}"'
    mode: '0600'
    state: present

#Create extra_vars.yml variables file.

- name: Add subscription_id line to extra_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.yml'
    line: 'subscription_id: {{ subscription_id }}'
    mode: '0600'
    state: present
    create: yes

- name: Add member_id line to extra_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.yml'
    line: 'member_id: {{ member_id }}'
    mode: '0600'
    state: present

- name: Add client_email line to extra_vars.yml file locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.yml'
    line: 'client_email: {{ client_email }}'
    mode: '0600'
    state: present


