

- name: Set sub type strings
  set_fact:
    digitalocean_string: 'DigitalOcean'
    on_premise_string: 'On-Premise'

- name: Configure subscription_type 1
  set_fact:
    subscription_type: 'digitalocean'
  when: digitalocean_string in plan_title
  
- name: Configure subscription_type 2
  set_fact:
    subscription_type: 'on_premise'
  when: on_premise_string in plan_title

- debug:
    msg: "subscription_type: {{ subscription_type }}"

- name: Ensure AWX projects directory has correct permissions
  file:
    path: '/var/'
    state: directory
    mode: '0755'

- name: Ensure AWX projects directory has correct permissions
  file:
    path: '/var/lib/'
    state: directory
    mode: '0755'
 
- name: Ensure AWX projects directory has correct permissions
  file:
    path: '/var/lib/awx/'
    state: directory
    mode: '0755'

- name: Ensure AWX projects directory has correct permissions
  file:
    path: '/var/lib/awx/projects/'
    state: directory
    mode: '0755'

- name: Ensure AWX projects directory has correct permissions
  file:
    path: '/var/lib/awx/projects/clients/'
    state: directory
    mode: '0711'

- name: Ensure users directory exists and has correct permissions
  file:
    path: '/var/lib/awx/projects/clients/{{ member_id }}/'
    state: directory
    mode: '0711'

- name: Create a directory for that subscription
  file:
    path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/'
    state: directory
    mode: '0700'

# Create server_vars.yml file locally on AWX.

- name: Touch the same file, but add/remove some permissions
  file:
    path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    state: touch
    mode: '0600'

- name: Add do_image line to server_vars.yml file locally on AWX
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'do_image: {{ do_image_master }}'
    mode: '0600'
    state: present
  when: subscription_type == 'digitalocean'

- name: Add do_image line to server_vars.yml file locally on AWX
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'subscription_type: {{ subscription_type }}'
    mode: '0600'
    state: present

- name: Add plan_title line to server_vars.yml file locally on AWX
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/server_vars.yml'
    line: 'plan_title: {{ plan_title }}'
    mode: '0600'
    state: present

# Create organisation.yml file
  
- name: Touch the same file, but add/remove some permissions
  file:
    path: '/var/lib/awx/projects/clients/{{ member_id }}/organisation.yml'
    mode: '0660'
#    user: root
#    group: webhook
    state: touch
    
#- name: Change owner:group of the organisation.yml file
#  command: chown root:webhook /var/lib/awx/projects/clients/{{ member_id }}/organisation.yml

# https://github.com/ansible/ansible/issues/73269

- name: Add client_email line to organisation.yml file locally on AWX
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/organisation.yml'
    line: 'client_email: "{{ client_email }}"'
    mode: '0660'
    owner: root
    group: webhook
    state: present

- name: Add member_id line to organisation.yml file locally on AWX
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/organisation.yml'
    line: 'member_id: "{{ member_id }}"'
    mode: '0660'
    owner: root
    group: webhook
    state: present

- name: Add client_first_name line to organisation.yml file locally on AWX
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/organisation.yml'
    line: 'client_first_name: "{{ client_first_name }}"'
    mode: '0660'
    owner: root
    group: webhook
    state: present

- name: Add client_last_name line to organisation.yml file locally on AWX
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/organisation.yml'
    line: 'client_last_name: "{{ client_last_name }}"'
    mode: '0660'
    owner: root
    group: webhook
    state: present

#Create extra_vars.yml variables file.

- name: Add subscription_id line to extra_vars.yml file locally on AWX
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.yml'
    line: 'subscription_id: {{ subscription_id }}'
    mode: '0600'
    state: present
    create: yes

- name: Add member_id line to extra_vars.yml file locally on AWX
  lineinfile:
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.yml'
    line: 'member_id: {{ member_id }}'
    mode: '0600'
    state: present


