
- name: touch, just a little touch
  command: |
    whoami

- name: touch, just a little touch
  command: |
    touch /runner/test

#- name: touch, just a little touch
#  command: |
#    hostname

#- name: touch, just a little touch
#  command: |
#    ip a

- name: touch, just a little touch
  file:
    path: /var/lib/awx/projects/touch
    state: touch

- name: Include hosting vars of hosting_vars.yml
  include_vars:
    file: /var/lib/awx/projects/hosting/hosting_vars.yml
#  no_log: True

- name: Include AWX master token from awx_tokens.yml
  include_vars:
    file: /var/lib/awx/projects/hosting/awx_tokens.yml
  no_log: True
