
- name: Include hosting vars of hosting_vars.yml
  include_vars:
    file: /var/lib/awx/projects/hosting/hosting_vars.yml
  when: cancel_deletion|bool
  no_log: True

- name: Include AWX master token from awx_tokens.yml
  include_vars:
    file: /var/lib/awx/projects/hosting/awx_tokens.yml
  no_log: True

- name: Create a AWX session token for executing modules
  awx.awx.tower_token:
    description: 'AWX Session Token'
    scope: "write"
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_master_token }}"
  register: awx_session_token

- name: Remove schedule for '<< SUBSCRIPTION DELETION IN PROGRESS >>' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_schedule:
    name: "{{ subscription_id }} - << SUBSCRIPTION DELETION IN PROGRESS >>"
    enabled: yes
    state: absent
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: cancel_deletion|bool

- name: Grant execute permission on 'Deploy/Update a Server' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_role:
    team: "{{ member_id }}"
    job_template: "{{ matrix_domain }} - 0 - Deploy/Update a Server"
    role: execute
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool)
  
- name: Grant execute permission on 'Backup Server' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_role:
    team: "{{ member_id }}"
    job_template: "{{ matrix_domain }} - 0 - Backup Server"
    role: execute
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool) 

- name: Grant execute permission on 'Self-Check' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_role:
    team: "{{ member_id }}"
    job_template: "{{ matrix_domain }} - 0 - Self-Check"
    role: execute
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool)

- name: Grant execute permission on 'Start/Restart all Services' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_role:
    team: "{{ member_id }}"
    job_template: "{{ matrix_domain }} - 0 - Start/Restart all Services"
    role: execute
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool)

- name: Grant execute permission on 'Stop all Services' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_role:
    team: "{{ member_id }}"
    job_template: "{{ matrix_domain }} - 0 - Stop all Services"
    role: execute
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool)

- name: Grant execute permission on 'Configure Corporal (Advanced)' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_role:
    team: "{{ member_id }}"
    job_template: "{{ matrix_domain }} - 1 - Configure Corporal (Advanced)"
    role: execute
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool)

- name: Grant execute permission on 'Configure Dimension' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_role:
    team: "{{ member_id }}"
    job_template: "{{ matrix_domain }} - 1 - Configure Dimension"
    role: execute
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool)

- name: Grant execute permission on 'Configure Element' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_role:
    team: "{{ member_id }}"
    job_template: "{{ matrix_domain }} - 1 - Configure Element"
    role: execute
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool)

- name: Grant execute permission on 'Configure Element Subdomain' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_role:
    team: "{{ member_id }}"
    job_template: "{{ matrix_domain }} - 1 - Configure Element Subdomain"
    role: execute
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool)

- name: Grant execute permission on 'Configure Email Relay' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_role:
    team: "{{ member_id }}"
    job_template: "{{ matrix_domain }} - 1 - Configure Email Relay"
    role: execute
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool)

- name: Grant execute permission on 'Configure Jitsi' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_role:
    team: "{{ member_id }}"
    job_template: "{{ matrix_domain }} - 1 - Configure Jitsi"
    role: execute
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool)

- name: Grant execute permission on 'Configure ma1sd (Advanced)' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_role:
    team: "{{ member_id }}"
    job_template: "{{ matrix_domain }} - 1 - Configure ma1sd (Advanced)"
    role: execute
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool)

- name: Grant execute permission on 'Configure Synapse' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_role:
    team: "{{ member_id }}"
    job_template: "{{ matrix_domain }} - 1 - Configure Synapse"
    role: execute
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool)

- name: Grant execute permission on 'Configure Synapse Admin' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_role:
    team: "{{ member_id }}"
    job_template: "{{ matrix_domain }} - 1 - Configure Synapse Admin"
    role: execute
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool)

- name: Grant execute permission on 'Create User' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_role:
    team: "{{ member_id }}"
    job_template: "{{ matrix_domain }} - 2 - Create User"
    role: execute
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool)

- name: Grant execute permission on 'Purge Media (Advanced)' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_role:
    team: "{{ member_id }}"
    job_template: "{{ matrix_domain }} - 2 - Purge Media (Advanced)"
    role: execute
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool)

- name: Grant execute permission on 'Purge Database (Advanced)' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_role:
    team: "{{ member_id }}"
    job_template: "{{ matrix_domain }} - 2 - Purge Database (Advanced)"
    role: execute
    state: present
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool)

- name: Execute 'Start/Restart all Services' job template
  delegate_to: 127.0.0.1
  awx.awx.tower_job_launch:
    job_template: "{{ matrix_domain }} - 0 - Start/Restart all Services"
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  register: job
  when: (matrix_domain is defined) and (cancel_deletion|bool)

- name: Wait for job max 300s
  awx.awx.tower_job_wait:
    job_id: "{{ job.id }}"
    timeout: 300
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  ignore_errors: yes
  when: (matrix_domain is defined) and (cancel_deletion|bool)

- name: Save new 'Delete Job Template' survey.json to the AWX tower, template
  delegate_to: 127.0.0.1
  template:
    src: '{{ role_path }}/templates/cleanup_deletion_template_deployed.json.j2'
    dest: '/var/lib/awx/projects/hosting/cleanup_deletion_template-{{ subscription_id }}.json'
  when: (matrix_domain is defined) and (cancel_deletion|bool)
  
- name: Save new 'Delete Job Template' survey.json to the AWX tower, template
  delegate_to: 127.0.0.1
  template:
    src: '{{ role_path }}/templates/cleanup_deletion_template.json.j2'
    dest: '/var/lib/awx/projects/hosting/cleanup_deletion_template-{{ subscription_id }}.json'
  when: (matrix_domain is undefined) and (cancel_deletion|bool)

- name: Re-create '00 - Cleanup Deletion Template' job template
  awx.awx.tower_job_template:
    name: "00 - Cleanup Deletion Template"
    description: "Deletes the remaining '<< SUBSCRIPTION DELETION IN PROGRESS >>' job template."
    job_type: run
    inventory: "{{ org_name }} [Admin]"
    project: "Ansible Create Delete Subscription Membership"
    playbook: cleanup_deletion_job_template.yml
    extra_vars: "{{ lookup('file', '/var/lib/awx/projects/hosting/cleanup_deletion_template-{{ subscription_id }}.json') }}"
    ask_extra_vars: yes
    state: present
    verbosity: 1
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes
  when: cancel_deletion|bool

- name: Launch '00 - Cleanup Deletion Template' job template before ending
  awx.awx.tower_job_launch:
    job_template: "00 - Cleanup Deletion Template"
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: yes 
  when: cancel_deletion|bool

- name: Delete the AWX session token for executing modules
  awx.awx.tower_token:
    description: 'AWX Session Token'
    scope: "write"
    state: absent
    existing_token_id: "{{ awx_session_token.ansible_facts.tower_token.id }}"
    tower_host: "https://{{ awx_host }}"
    tower_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
  when: cancel_deletion|bool

- name: Set boolean value to exit playbook
  set_fact:
    end_playbook: true
  when: cancel_deletion|bool

- name: End playbook if this task list is called.
  meta: end_play
  when: (end_playbook is defined) and end_playbook|bool and cancel_deletion|bool
