
- name: Include matrix server variables from matrix_vars.yml
  delegate_to: 127.0.0.1
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - /var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml
      skip: true
  no_log: True

- name: Install curl in AWX
  delegate_to: 127.0.0.1
  yum:
    name: curl
    state: latest

- name: Delete MailGun SMTP login
  delegate_to: 127.0.0.1
  shell: |
    curl -s --user 'api:{{ mg_private_api_key }}' -X DELETE https://{{ mg_api_url }}/v3/domains/{{ mg_sender_domain }}/credentials/{{ matrix_domain }}
  when: matrix_domain is defined
  no_log: True
