
# Abort Subscription Deletion
- import_tasks: "{{ role_path }}/tasks/abort_deletion.yml"
  tags: delete-subscription

# Delete DigitalOcean Droplet/Space
- import_tasks: "{{ role_path }}/tasks/delete_server.yml"
  tags: delete-subscription

# Delete MailGun SMTP Account
- import_tasks: "{{ role_path }}/tasks/delete_mailgun.yml"
  tags: delete-subscription

# Delete AWX Job Templates for Server
- import_tasks: "{{ role_path }}/tasks/delete_awx_templates.yml"
  tags: delete-subscription

# Move the Servers Backup Directory
- import_tasks: "{{ role_path }}/tasks/move_backup_directory.yml"
  tags: delete-subscription

# Delete Organisation Directories
- import_tasks: "{{ role_path }}/tasks/delete_subscription_directory.yml"
  tags: delete-subscription
